#!/bin/sh
# Regenerates vendor/headroom/requirements.txt from requirements.in, with the hashes of every distribution
# of every pinned package, for all platforms. Run it in Linux (a microVM or container) with network access:
#
#   scripts/headroom-bundle/lock.sh
set -eu
root=$(cd "$(dirname "$0")/../.." && pwd)
python3 -m pip install --quiet --disable-pip-version-check uv
cd "$root/vendor/headroom"
{
  echo '# Generated by scripts/headroom-bundle/lock.sh from requirements.in: every package the Headroom bundle'
  echo '# installs, pinned with the sha256 of each of its distributions (all platforms), installed with'
  echo '# `pip install --require-hashes --no-deps`. Do not edit by hand.'
  python3 -m uv pip compile requirements.in --universal --generate-hashes --python-version 3.13 --no-header
} > requirements.txt.new
mv requirements.txt.new requirements.txt
echo "locked $(grep -cE '^[A-Za-z0-9_.-]+==' requirements.txt) packages"
