#!/usr/bin/env node
// A long document can be split into a directory of per-area files, one per feature, so two pull
// requests stop editing the same page; `docs/protocol.md` and `docs/loops.md` do this. The index at
// the top of the parent file lists each area file, and when that list is kept by hand it drifts the
// moment someone adds a file. This script keeps it honest: a block between `<!-- doc-index:start -->`
// and `<!-- doc-index:end -->` is exactly one line per file under `docs/<name>/`, sorted by file
// name, `- [<the file's h1>](<name>/<file>.md)`.
//
//   node scripts/doc-index.mjs check    every docs/<name>.md index matches its docs/<name>/ directory
//   node scripts/doc-index.mjs write    rewrite the blocks to match
//
// Only `docs/<name>.md` files that already carry the markers are touched; a file with no directory
// beside it has an empty block. Like the other scripts under scripts/, the pure helpers are exported
// so scripts/test/doc-index.test.mjs can pin them without running `main`.
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export const START = '<!-- doc-index:start -->';
export const END = '<!-- doc-index:end -->';

/** The heading text of a Markdown document's first `#` line, or null. */
export function h1(markdown) {
  for (const line of markdown.split('\n')) {
    const m = line.match(/^#\s+(.*?)\s*#*\s*$/);
    if (m) return m[1];
  }
  return null;
}

/** The line the writer puts just above the start marker, so a reader knows the block is generated. */
export function note(name) {
  return `Generated by \`node scripts/doc-index.mjs write\`: add a file under docs/${name}/ and rerun; don't edit by hand.`;
}

/** `[{ file, title }]` for every `*.md` under `docs/<name>`, sorted by file name. */
export function entries(root, name) {
  const dir = join(root, 'docs', name);
  let names;
  try {
    names = readdirSync(dir).filter((f) => f.endsWith('.md') && statSync(join(dir, f)).isFile());
  } catch {
    return [];
  }
  names.sort();
  return names.map((file) => ({ file, title: h1(readFileSync(join(dir, file), 'utf8')) }));
}

/** The block body: one `- [title](name/file.md)` line per entry, in the order given (already sorted). */
export function renderBody(name, entries) {
  return entries.map((e) => `- [${e.title}](${name}/${e.file})`).join('\n');
}

/** The markers `{ start, end }` positions in `text`, or null when either is missing. */
export function markers(text) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start === -1 || end === -1 || end < start) return null;
  return { start, end };
}

/** The text between the two markers, without the marker lines. */
export function body(text) {
  const m = markers(text);
  if (!m) return null;
  return text.slice(m.start + START.length, m.end).replace(/^\n/, '').replace(/\n$/, '');
}

/** `text` with the block body replaced by `renderBody(name, entries)`, keeping the markers. */
export function applyBlock(text, name, entries) {
  const m = markers(text);
  if (!m) return text;
  const body = renderBody(name, entries);
  return `${text.slice(0, m.start + START.length)}\n${body}\n${text.slice(m.end)}`;
}

/** Same as `applyBlock`, but also makes sure the `note` line sits directly above the start marker. */
export function applyNote(text, name) {
  const m = markers(text);
  if (!m) return text;
  const before = text.slice(0, m.start);
  const line = note(name);
  if (before.endsWith(`${line}\n`)) return text;
  const trimmed = before.replace(/\n*\s*$/, '\n\n');
  return `${trimmed}${line}\n${text.slice(m.start)}`;
}

/** Problems in one index file's text as `path: message` strings; empty when it is correct. */
export function checkText(file, text, name, entries) {
  const problems = [];
  const m = markers(text);
  if (!m) return [`${file}: no ${START} … ${END} block`];
  const expected = renderBody(name, entries);
  const found = body(text);
  if (found !== expected) {
    problems.push(`${file}: the index does not match docs/${name}/ — run \`node scripts/doc-index.mjs write\``);
  }
  if (!text.slice(0, m.start).endsWith(`${note(name)}\n`)) {
    problems.push(`${file}: the "Generated by …" note is missing just above ${START}`);
  }
  return problems;
}

/** Every `docs/<name>.md` that carries the markers, as `{ file, name }`. */
export function indexFiles(root = ROOT) {
  const docs = join(root, 'docs');
  return readdirSync(docs)
    .filter((f) => f.endsWith('.md'))
    .map((f) => ({ file: `docs/${f}`, name: f.slice(0, -'.md'.length) }))
    .filter(({ file }) => {
      try {
        return readFileSync(join(root, file), 'utf8').includes(START);
      } catch {
        return false;
      }
    });
}

function main(argv = process.argv.slice(2)) {
  const command = argv[0] ?? 'check';
  if (command !== 'check' && command !== 'write') {
    console.error('usage: node scripts/doc-index.mjs [check|write]');
    return 1;
  }
  const files = indexFiles();
  if (!files.length) {
    console.error(`no docs/<name>.md carries a ${START} block`);
    return 1;
  }
  let failed = 0;
  for (const { file, name } of files) {
    const path = join(ROOT, file);
    const text = readFileSync(path, 'utf8');
    const list = entries(ROOT, name);
    if (command === 'write') {
      const next = applyNote(applyBlock(text, name, list), name);
      if (next !== text) writeFileSync(path, next);
      console.log(`${file}: ${list.length} area file(s)`);
      continue;
    }
    const problems = checkText(file, text, name, list);
    for (const p of problems) console.error(p);
    if (problems.length) failed++;
  }
  if (command === 'check') {
    if (failed) {
      console.error(`\n${failed} index file(s) out of date.`);
      return 1;
    }
    console.log(`${files.length} index file(s): every area list is up to date.`);
  }
  return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  try {
    process.exit(main());
  } catch (e) {
    console.error(`doc-index.mjs ${process.argv[2] ?? ''} failed unexpectedly: ${e.stack ?? e}`);
    process.exit(1);
  }
}
