// scripts/doc-index.mjs: a docs/<name>.md that splits into docs/<name>/*.md keeps a generated list
// of its area files honest. The helpers are exercised on a throwaway tree, and the last test runs
// the real check over this repository so a new area file without a rerun fails CI.
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { after, test } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  END,
  START,
  applyBlock,
  applyNote,
  body,
  checkText,
  entries,
  h1,
  indexFiles,
  markers,
  note,
  renderBody,
} from '../doc-index.mjs';

const SCRIPT = resolve(dirname(fileURLToPath(import.meta.url)), '../doc-index.mjs');
const scratch = mkdtempSync(join(tmpdir(), 'doc-index-'));
after(() => rmSync(scratch, { recursive: true, force: true }));

/** A throwaway tree written from `{ path: text }`, under the shared scratch directory. */
function tree(files) {
  const root = mkdtempSync(join(scratch, 'root-'));
  for (const [p, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, p)), { recursive: true });
    writeFileSync(join(root, p), text);
  }
  return root;
}

const INDEX = (name, list) =>
  `# ${name}\n\n${note(name)}\n${START}\n${list}\n${END}\n`;

test('h1 reads the first level-1 heading and nothing else', () => {
  assert.equal(h1('# Title\n\ntext\n## Not this\n'), 'Title');
  assert.equal(h1('## Only a sub\n'), null);
});

test('entries lists *.md sorted by file name and reads each h1', () => {
  const root = tree({
    'docs/protocol/b.md': '# Bee\n',
    'docs/protocol/a.md': '# Ay\n',
    'docs/protocol/notes.txt': 'ignored\n',
  });
  assert.deepEqual(entries(root, 'protocol'), [
    { file: 'a.md', title: 'Ay' },
    { file: 'b.md', title: 'Bee' },
  ]);
  assert.deepEqual(entries(root, 'missing'), []);
});

test('renderBody is one bullet per entry, in the order given', () => {
  assert.equal(
    renderBody('protocol', [
      { file: 'a.md', title: 'A' },
      { file: 'b.md', title: 'B' },
    ]),
    '- [A](protocol/a.md)\n- [B](protocol/b.md)',
  );
});

test('markers and body find the block, and applyBlock rewrites only its inside', () => {
  const text = INDEX('protocol', '- [A](protocol/a.md)');
  assert.ok(markers(text));
  assert.equal(body(text), '- [A](protocol/a.md)');
  const next = applyBlock(text, 'protocol', [{ file: 'b.md', title: 'B' }]);
  assert.match(next, /- \[B\]\(protocol\/b\.md\)/);
  assert.ok(!next.includes('(protocol/a.md)'));
  assert.equal(markers(next).start, markers(text).start);
  assert.ok(next.includes(START) && next.endsWith(`${END}\n`));
});

test('applyNote puts the "Generated by …" line just above the start marker', () => {
  const bare = `# protocol\n\n${START}\n- [A](protocol/a.md)\n${END}\n`;
  const withNote = applyNote(bare, 'protocol');
  assert.ok(withNote.includes(`${note('protocol')}\n${START}`));
  assert.equal(applyNote(withNote, 'protocol'), withNote); // idempotent
});

test('checkText is quiet on a correct index and names the file when it is stale', () => {
  const root = tree({
    'docs/protocol/a.md': '# A\n',
    'docs/protocol/b.md': '# B\n',
    'docs/protocol.md': INDEX('protocol', '- [A](protocol/a.md)\n- [B](protocol/b.md)'),
  });
  const text = readFileSync(join(root, 'docs/protocol.md'), 'utf8');
  const list = entries(root, 'protocol');
  assert.deepEqual(checkText('docs/protocol.md', text, 'protocol', list), []);

  const stale = text.replace('- [A](protocol/a.md)\n- [B](protocol/b.md)', '- [A](protocol/a.md)');
  const problems = checkText('docs/protocol.md', stale, 'protocol', list);
  assert.equal(problems.length, 1);
  assert.match(problems[0], /docs\/protocol\.md/);
  assert.match(problems[0], /doc-index\.mjs write/);

  assert.deepEqual(checkText('docs/protocol.md', '# no markers\n', 'protocol', list), [
    `docs/protocol.md: no ${START} … ${END} block`,
  ]);
});

test('indexFiles finds only docs/<name>.md files that carry the markers', () => {
  const root = tree({
    'docs/protocol.md': INDEX('protocol', '- [A](protocol/a.md)'),
    'docs/plain.md': '# Plain\n',
    'docs/protocol/a.md': '# A\n',
  });
  assert.deepEqual(indexFiles(root), [{ file: 'docs/protocol.md', name: 'protocol' }]);
});

test("this repository's doc indexes are up to date", () => {
  execFileSync(process.execPath, [SCRIPT, 'check'], { stdio: 'pipe' });
});
